### ISSUE TITLE
NameError: name 'k' is not defined

### ISSUE THREAD

**Issue by kaustabpal** [Keith-Campbell/interior_point_method_for_QP#1]
I am trying to run the code and getting the following error:
```bash
Traceback (most recent call last):
  File "ip.py", line 132, in <module>
    main()
  File "ip.py", line 124, in main
    [xk, yk, lk] = solve()
  File "ip.py", line 81, in solve
    solveapprxKKT(init_x,init_y,init_l,zeros((m,m)),zeros((m,m)),0)
  File "ip.py", line 49, in solveapprxKKT
    rp = A@k - b - yk
NameError: name 'k' is not defined
```
Kindly let me know how to resolve this issue.

**Comment by a24hori** [comment]
Thanks for running my code.
The name 'k' should be 'xk'.
